version: '3.8'

services:
  kibana:
    image: kibana:7.17.9
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://host.docker.internal:9200
    networks:
      - elastic

networks:
  elastic:
    driver: bridge